DECLARE
  LF_ETA DATE;
  LN_PUERTO_SALIDA VARCHAR2(20);
  LN_PUERTO_LLEGADA VARCHAR2(20);
  LF_SALIDA DATE;
  LF_LLEGADA DATE;
  LK_NUM_SERIE NUMBER;
  LV_CARGATRANSPORTADA NUMBER;
  LK_ID_AGENTE VARCHAR2(20);
  LN_SENTIDO VARCHAR2(6);
BEGIN
  LF_ETA := to_date('2019/02/10','yyyy/mm/dd');
  LN_PUERTO_SALIDA := 'Puerto wilches';
  LN_PUERTO_LLEGADA := 'Puerto Colombia';
  LF_SALIDA := to_date('2019/02/10','yyyy/mm/dd');
  LF_LLEGADA := to_date('2019/02/10','yyyy/mm/dd');
  LK_NUM_SERIE := 123;
  LV_CARGATRANSPORTADA := 10;
  LK_ID_AGENTE := 1;
  LN_SENTIDO := 'Norte';

  PR_REGISTRAR_RESERVA(
    LF_ETA => LF_ETA,
    LN_PUERTO_SALIDA => LN_PUERTO_SALIDA,
    LN_PUERTO_LLEGADA => LN_PUERTO_LLEGADA,
    LF_SALIDA => LF_SALIDA,
    LF_LLEGADA => LF_LLEGADA,
    LK_NUM_SERIE => LK_NUM_SERIE,
    LV_CARGATRANSPORTADA => LV_CARGATRANSPORTADA,
    LK_ID_AGENTE => LK_ID_AGENTE,
    LN_SENTIDO => LN_SENTIDO
  );
--rollback; 
END;
