DECLARE
  PF_ETA DATE;
  PN_PUERTO_SALIDA VARCHAR2(20);
  PN_PUERTO_LLEGADA VARCHAR2(20);
  PK_NUM_SERIE NUMBER;
  PV_CARGATRANSPORTADA NUMBER;
  PN_SENTIDO VARCHAR2(6);
BEGIN
  PF_ETA := to_date('15/04/2019','dd/mm/yyyy');
  PN_PUERTO_SALIDA := NULL;
  PN_PUERTO_LLEGADA := NULL;
  PK_NUM_SERIE := 123;
  PV_CARGATRANSPORTADA := 10;
  PN_SENTIDO := 'Sur';

  PR_REGISTRAR_RESERVA(
    PF_ETA => PF_ETA,
    PN_PUERTO_SALIDA => PN_PUERTO_SALIDA,
    PN_PUERTO_LLEGADA => PN_PUERTO_LLEGADA,
    PK_NUM_SERIE => PK_NUM_SERIE,
    PV_CARGATRANSPORTADA => PV_CARGATRANSPORTADA,
    PN_SENTIDO => PN_SENTIDO
  );
--rollback; 
END;