/* CREACIÓN DE BANCOS*/
INSERT INTO banco (k_id,n_nombre)
	VALUES (1,'BBVA');
	
INSERT INTO banco (k_id,n_nombre)
	VALUES (2,'JP Morgan Chase');
	
INSERT INTO banco (k_id,n_nombre)
	VALUES (3,'Bank of America');

INSERT INTO banco (k_id,n_nombre)
	VALUES (4,'Bank of China');
	
INSERT INTO banco (k_id,n_nombre)
	VALUES (5,'Bank Of Montreal');
/* CREACIÓN DE TITULARES*/
INSERT INTO titular (k_id,n_nombre,n_apellido)
	VALUES (5,'Arturo','Perez');

	

	

	