-- DENTRO DE SYSTEM --
/*
CREATE TABLESPACE canalPanDatos DATAFILE 'C:\temporal\canalPanDatos.DBF' SIZE 1024M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TEMPORARY TABLESPACE canalPanTemp TEMPFILE 'C:\temporal\canalPanTemp.DBF' SIZE 300M;

CREATE TABLESPACE PepAgDatos DATAFILE 'C:\temporal\PepAgDatos.DBF' SIZE 500M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TEMPORARY TABLESPACE PepAgDatosTemp TEMPFILE 'C:\temporal\PepAgDatosTemp.DBF' SIZE 200M;

CREATE TABLESPACE CamAgDatos DATAFILE 'C:\temporal\CamAgDatos.DBF' SIZE 500M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TEMPORARY TABLESPACE CamAgDatosTemp TEMPFILE 'C:\temporal\CamAgDatosTemp.DBF' SIZE 200M;

CREATE USER CanalDePanama IDENTIFIED BY panamaUD DEFAULT TABLESPACE canalPanDatos TEMPORARY TABLESPACE canalPanTemp;

GRANT dba, connect, resource TO CanalDePanama;


CREATE PUBLIC SYNONYM PR_REGISTRAR_RESERVA FOR canalDePanama.PR_REGISTRAR_RESERVA;

--- Usuarios del sistema con rol Agente ---
CREATE USER ANTHONY IDENTIFIED BY anthony;
CREATE USER PepeAgente IDENTIFIED BY pepe111 DEFAULT TABLESPACE PepAgDatos TEMPORARY TABLESPACE PepAgDatosTemp;
CREATE USER CamiloAgente IDENTIFIED BY camilo111 DEFAULT TABLESPACE CamAgDatos TEMPORARY TABLESPACE CamAgDatosTemp;

*/
/* DENTRO DE CANAL DE PANAMA */

