CREATE TABLESPACE canalPanDatos DATAFILE 'C:\temporal\canalPanDatos.DBF' SIZE 1024M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TEMPORARY TABLESPACE canalPanTemp TEMPFILE 'C:\temporal\canalPanTemp.DBF' SIZE 300M;

CREATE TABLESPACE PepAgDatos DATAFILE 'C:\temporal\PepAgDatos.DBF' SIZE 500M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TEMPORARY TABLESPACE PepAgDatosTemp TEMPFILE 'C:\temporal\PepAgDatosTemp.DBF' SIZE 200M;

CREATE USER CanalDePanama IDENTIFIED BY panamaUD DEFAULT TABLESPACE canalPanDatos TEMPORARY TABLESPACE canalPanTemp;

CREATE USER PepeAgente IDENTIFIED BY pepe111 DEFAULT TABLESPACE PepAgDatos TEMPORARY TABLESPACE PepAgDatosTemp;
 

GRANT dba, connect, resource TO CanalDePanama;


CREATE ROLE Agente;

GRANT connect TO Agente;

GRANT SELECT ON Agente TO Agente;
GRANT SELECT ON pasosAgente TO Agente;
GRANT SELECT ON paso TO  Agente;

GRANT Agente TO PepeAgente;